---
# SPDX-FileCopyrightText: 2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include init_ansible"
      ansible.builtin.include_role:
        name: init_ansible
