---
# SPDX-FileCopyrightText: 2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install OpenSSH server
      ansible.builtin.apt:
        name: openssh-server
        state: present
