---
# SPDX-FileCopyrightText: 2024-2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later
- name: Restart Gunicorn service
  service:
    name: gunicorn
    state: restarted
  become: yes

- name: Restart web server
  service:
    name: nginx
    state: restarted
  become: yes

- name: Restart Celery Service
  systemd:
    name: celery
    state: restarted
  become: yes
