---
- name: Restart Gunicorn service
  service:
    name: gunicorn
    state: restarted
  become: yes

- name: Restart web server
  service:
    name: nginx
    state: restarted
  become: yes

- name: Restart Celery Service
  systemd:
    name: celery
    state: restarted
  become: yes
