namespace: t4d
name: WebServerSetup
version: 1.0.0
description: Ansible collection for automating the setup and management of web servers, specifically tailored for deploying Django applications.
readme: README.md
license: GNU GPLv3
authors:
  - "Jonas I Liechti <j-i-l@t4d.ch>"
tags:
  - webserver
  - automation
  - django
  - ansible
  - security
  - database
dependencies:
  - community.docker
