---
osbackupper:
  backup_dir: /var/backups/openstack-vm-snapshots
  keep_days: 7
  keep_weeks: 4
  keep_months: 6
  user: backupuser
  venv: /opt/openstack-backup-venv
  service_name: openstack-vm-backup
  run_at: "02:00:00"
  package_version: "0.1.0"
  package_src: "{{ playbook_dir | default('.') }}/src"
