# start from the base OpenCPU image
FROM {{ opencpu.DOCKER_IMAGE | default("docker.io/opencpu/ubuntu-24.04") }}:{{ opencpu.DOCKER_TAG | default("v2.2.14-2") }}

RUN apt-get update
RUN apt-get install -y --no-install-recommends libcurl4-openssl-dev
RUN rm -rf /var/lib/apt/lists/* 

# Install custom packages
{% for command in opencpu.RUN_R %}
RUN R -e "{{ command }}"
{% endfor %}
