---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install Python Docker dependencies
      ansible.builtin.apt:
        name:
          - python3-docker
          - docker-compose-v2
        state: present
        update_cache: true
