---
# SPDX-FileCopyrightText: 2025-2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart UFW
  become: true
  service:
    name: ufw
    state: restarted

- name: Restart SSH
  become: true
  service:
    name: ssh
    state: restarted
