# SPDX-FileCopyrightText: 2024-2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later
- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Reload Gunicorn
  systemd:
    name: gunicorn
    state: restarted
  become: yes
