---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Create test user
      ansible.builtin.user:
        name: testuser
        state: present

    - name: Install GPG (needed for apt_key module)
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
        state: present
        update_cache: true
