---
# SPDX-FileCopyrightText: 2026 Jonas I. Liechti <j-i-l@t4d.ch>
#
# SPDX-License-Identifier: GPL-3.0-or-later
role_name_check: 1
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /var/lib/docker:exec
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"
  inventory:
    host_vars:
      instance:
        dancer_user: testuser
        server_url: "https://nb.test.example.com"
        dns_provider: infomaniak
        email: "test@example.com"
        vault_netbird_auth_secret: "test-relay-auth-secret"
        vault_netbird_store_encryption_key: "dGVzdHRlc3R0ZXN0dGVzdHRlc3R0ZXN0dGVzdDEyMzQ="
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Skip idempotence - docker_compose_v2 interactions
    - verify
    - cleanup
    - destroy
