---
- name: Ensure ACL package is installed
  package:
    name: acl
    state: present
  become: yes

- name: Fetch the latest changes from the Git repository
  git:
    repo: "https://oauth2:{{ vault_repository_token }}@{{ git_remote }}{{ git_repository_path }}"
    dest: "/opt/{{ app_name }}"
    version: "{{ git_repository_branch }}"  # Specify the branch or tag you want to clone
    force: yes
  become: yes
  tags:
    - molecule-notest

- name: Create a virtual environment if it doesn't exist
  command: python3 -m venv /opt/{{ app_name }}/venv
  args:
    creates: /opt/{{ app_name }}/venv
  become: yes
  become_user: django  # Run this task as the django user
  tags:
    - molecule-notest

- name: Check for pyproject.toml
  stat:
    path: /opt/{{ app_name }}/pyproject.toml
  register: req_pyproject
  become: yes

- name: Check for requirements.txt
  stat:
    path: /opt/{{ app_name }}/requirements.txt
  register: req_txt
  become: yes

- name: Fail if neither pyproject.toml nor requirements.txt is present
  fail:
    msg: "Neither pyproject.toml nor requirements.txt found in /opt/{{ app_name }}"
  when: not req_pyproject.stat.exists and not req_txt.stat.exists
  tags:
    - molecule-notest

- name: Install requirements from pyproject.toml
  pip:
    name: /opt/{{ app_name }}
    virtualenv: /opt/{{ app_name }}/venv
  become: yes
  become_user: django
  when: req_pyproject.stat.exists
  tags:
    - molecule-notest

- name: Install requirements from requirements.txt
  pip:
    requirements: /opt/{{ app_name }}/requirements.txt
    virtualenv: /opt/{{ app_name }}/venv
  become: yes
  become_user: django
  when: not req_pyproject.stat.exists and req_txt.stat.exists
  tags:
    - molecule-notest

- name: Collect static files
  command: /opt/{{ app_name }}/venv/bin/python /opt/{{ app_name }}/{{ app_name | lower }}/manage.py collectstatic --noinput
  args:
    chdir: /opt/{{ app_name }}
  become: yes
  become_user: django  # Run this task as the django user
  notify:
    - Restart Gunicorn service  # Notify the handler
    - Restart Celery Service
    - Restart web server
  tags:
    - molecule-notest

- name: Apply database migrations
  command: /opt/{{ app_name }}/venv/bin/python /opt/{{ app_name }}/{{ app_name | lower }}/manage.py migrate
  args:
    chdir:
  register: migrate_result
  ignore_errors: yes
  tags:
    - molecule-notest

- name: Handle migration result
  block:
    - name: Show debug message if no migrations to apply
      debug:
        msg: "No migrations were applied."
      when: migrate_result.rc != 0 and "No migrations to apply" in migrate_result.stderr

    - name: Fail if migration failed for other reasons
      fail:
        msg: "Migration failed with an unexpected error: {{ migrate_result.stderr }}"
      when: migrate_result.rc != 0 and "No migrations to apply" not in migrate_result.stderr
  tags:
    - molecule-notest
