---
- name: Create Traefik configuration directory
  file:
    path: /data/docker/traefik
    state: directory
    owner: "{{ dancer_user }}"
    group: "{{ dancer_user }}"
    mode: '0755'

- name: Create Traefik configuration file
  template:
    src: traefik.yaml.j2
    dest: /data/docker/traefik/traefik.yaml
    owner: "{{ dancer_user }}"
    group: "{{ dancer_user }}"
    mode: '0644'

- name: Create Traefik docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /data/docker/traefik/docker-compose.yml
    owner: "{{ dancer_user }}"
    group: "{{ dancer_user }}"
    mode: '0644'

- name: Create .env file for Traefik
  template:
    src: .env.j2
    dest: /data/docker/traefik/.env
    owner: "{{ dancer_user }}"
    group: "{{ dancer_user }}"
    mode: '0644'

- name: Create Traefik users directory
  file:
    path: /data/docker/traefik/users
    state: directory
    # this should be owned by root

- name: Create the users file
  template:
    src: users.txt.j2
    dest: /data/docker/traefik/users/users.txt

- name: Ensure ACL package is installed
  package:
    name: acl
    state: present
  become: yes

- name: Install python3-passlib
  ansible.builtin.apt:
    name: python3-passlib
    state: present

    # - name: Create htpasswd file and add users
    #   htpasswd:
    #     path: /data/docker/traefik/users/users.txt
    #     name: "{{ item.name }}"
    #     password: "{{ item.password }}"
    #     state: present
    #   loop: "{{ HTPASSWD_USERS }}"
    #   no_log: true  # Suppress output for this task

- name: Start Traefik container
  community.docker.docker_compose_v2:
    project_src: /data/docker/traefik
    state: present
  become: yes
  become_user: "{{ dancer_user }}"
