---
- name: Update apt package index
  become: true
  apt:
    update_cache: yes

- name: Install required packages for Docker installation
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install Docker
  become: true
  apt:
    name:
      - docker.io
      - python3-docker
    state: present

- name: Ensure Docker service is running
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Pull PostgreSQL Docker image
  become: true
  community.docker.docker_image_pull:
    name: postgres
    tag: "{{ postgresql_version }}"
  register: pulled_image

- name: Remove existing PostgreSQL container if image tag changed
  become: true
  community.docker.docker_container:
    name: "{{ postgresql_container_name }}"
    state: absent
    force_kill: true
  when: pulled_image.changed

- name: Ensure host postgres data dir exists
  become: true
  file:
    path: "{{ postgresql_data_dir }}/pgdata"
    state: directory
    owner: 999
    group: 999
    mode: '0700'

- name: Create PostgreSQL container from specific tag
  become: true
  community.docker.docker_container:
    name: "{{ postgresql_container_name  }}"
    image: "postgres:{{ postgresql_version }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ postgresql_port }}:5432"
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ vault_db_password }}"
      PGDATA: "{{ postgresql_pgdata_parent }}/pgdata"
    volumes:
      - "{{ postgresql_data_dir }}:{{ postgresql_pgdata_parent }}"
