---
- name: Update apt package index
  apt:
    update_cache: yes
  become: true

- name: Install required packages for Docker installation
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: true

- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: true


- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Pull PostgreSQL Docker image
  community.docker.docker_image_pull:
    name: postgres
    tag: "{{ postgresql_version }}"
  register: pulled_image
  become: true

- name: Remove existing PostgreSQL container if image tag changed
  community.docker.docker_container:
    name: "{{ postgresql_container_name }}"
    state: absent
    force_kill: true
  when: pulled_image.changed
  become: true

- name: Ensure host postgres data dir exists
  file:
    path: "{{ postgresql_data_dir }}/pgdata"
    state: directory
    owner: 999
    group: 999
    mode: "0700"
  become: true

- name: Create PostgreSQL container from specific tag
  community.docker.docker_container:
    name: "{{ postgresql_container_name  }}"
    image: "postgres:{{ postgresql_version }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ postgresql_port }}:5432"
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ vault_db_password }}"
      PGDATA: "{{ postgresql_pgdata }}/pgdata"
    volumes:
      - "{{ postgresql_data_dir }}:{{ postgresql_pgdata_parent }}"
  become: true
